#!/data/data/com.termux/files/usr/bin/bash
echo -e "\e[34m Installing core files\e[0m"
cd && pkg install git -y >/dev/null 2>&1 && git clone https://github.com/CodyAvi/Metasploit-CodyAvi.git >/dev/null 2>&1 && cd Metasploit-CodyAvi && mv * /data/data/com.termux/files/home && cd && chmod 777 metasploit_by_ATM.sh >/dev/null 2>&1

apt update -y >/dev/null 2>&1
apt upgrade -y >/dev/null 2>&1
apt install python -y >/dev/null 2>&1
apt install python2 -y >/dev/null 2>&1
pkg upgrade -y -o Dpkg::Options::="--force-confnew" >/dev/null 2>&1
pkg install -y python autoconf bison clang coreutils curl findutils apr apr-util postgresql openssl readline libffi libgmp libpcap libsqlite libgrpc libtool libxml2 libxslt ncurses make ncurses-utils ncurses git wget unzip zip tar termux-tools termux-elf-cleaner pkg-config git ruby -o Dpkg::Options::="--force-confnew" >/dev/null 2>&1

python3 -m pip install --upgrade pip >/dev/null 2>&1
python3 -m pip install requests >/dev/null 2>&1


echo -e "\e[34m Installation Success!!\e[0m"
bash metasploit_by_ATM.sh
